name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Releasing
        run: |
          export VERSION="$(date +"%y").$(date +"%m").${GITHUB_RUN_NUMBER}"
          echo "releasing version v${VERSION}"
          gh release create --generate-notes v"${VERSION}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/v22
          spec-file: src/v22.yaml
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/v21
          spec-file: src/v21.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist