name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download openapi.json
        uses: actions/download-artifact@v2
        with:
          name: spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: v22.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui