name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  deployments: write

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Generate Swagger UI (v2.2)
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/v22
          spec-file: src/v22.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Swagger UI (v2.1)
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/v21
          spec-file: src/v21.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
